### PR TITLE
Improve the naming conventions of classes and methods in C# bindings

### PR DESCRIPTION
**Pull request by Mersho**
Here is the new updated version:

https://github.com/Mersho/ldk-garbagecollected/commits/UpdateBindingsCSharp

### CODE REVIEW

**Comment by aarani** [comment]
I guess function names like "decodeUint8Array"  needs to be updated as well

**Comment by overtongeist** [comment]
> I guess function names like "decodeUint8Array" needs to be updated as well

Agreed.

**Comment by overtongeist** [comment]
CI is red, why was a PR proposed if CI is still red?

**Comment by Mersho** [comment]
> CI is red, why was a PR proposed if CI is still red?

The `c_sharp_bindings` job is fine, but I'm not understanding why `macos_determinism` is failing. However, I'm going to investigate it.

**Comment by overtongeist** [comment]
Just looked at the logs and my suspicion is that a re-run will work (of course I'm talking only about the CI of the 1st commit).

**Comment by Mersho** [comment]
After comparing the logs with upstream I realized the problem:

It's related to `git describe --tag HEAD`. In the CI, a `curl SNAPSHOT_LINK` command is executed based on `git describe --tag HEAD`

There's two solutions:

1. Removing this job like other jobs
2. Use `git describe --tag --abbrev=0` instead of `git describe --tag HEAD` (I'm not 100% sure about this solution)

If you approve and let me: I also going to remove that job.

**Comment by aarani** [comment]
This project needs to be on a tag, as the error message clearly says.

**Comment by Mersho** [comment]
> This project needs to be on a tag, as the error message clearly says.

You're looking at the wrong place (PR CI)...
let me explain `git describe --tag HEAD` output:

`v0.0.121.2-3-gc27c3b4f`:

`v0.0.121.2`: The most recent reachable tag is v0.0.121.2.
`3`: There are 3 additional commits after the v0.0.121.2 tag.
`gc27c3b4f`: The g stands for "git", and c27c3b4 is the abbreviated commit hash of HEAD.

**Comment by overtongeist** [comment]
Superseded by https://github.com/packwallet/ldk-garbagecollected/pull/4

**Pull request closed without merging**
